# NUMPY

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

Kita dapat mengakses elemen dalam array menggunakan tanda kurung siku. Saat kalian mengakses elemen, ingatlah bahwa pengindeksan di NumPy dimulai dari 0. Artinya, jika kalian ingin mengakses elemen pertama dalam array, kalian akan mengakses elemen "0".

In [8]:
print(a[0])

[1 2 3 4]


## 1D array, 2D array, ndarray, vector, matrix

Kalian mungkin sesekali mendengar array yang disebut sebagai "ndarray", yang merupakan singkatan dari "N-dimensional array.". Array berdimensi-N hanyalah array dengan sejumlah dimensi. Kalian mungkin juga mendengar array 1-D, atau array satu dimensi, 2-D, atau array dua dimensi, dan seterusnya. Kelas ndarray NumPy digunakan untuk merepresentasikan matriks dan vektor. Vektor adalah array dengan satu kolom, sedangkan matriks mengacu pada array dengan banyak kolom.

**What are the attributes of an array?**

Array biasanya merupakan fixed-size container of items dengan jenis dan ukuran yang sama. Jumlah dimensi dan item dalam array ditentukan oleh bentuknya. Bentuk array adalah tuple bilangan bulat non-negatif yang menentukan ukuran setiap dimensi.

Dalam NumPy, dimensi disebut axes. Artinya jika kalian memiliki array 2D yang terlihat seperti ini:

In [9]:
[[0., 0., 0.],
 [1., 1., 1.]]

[[0.0, 0.0, 0.0], [1.0, 1.0, 1.0]]

Array kalian memiliki 2 axes. Axis pertama memiliki panjang 2 dan axis kedua memiliki panjang 3.

Sama seperti di objek kontainer Python lainnya, konten array dapat diakses dan dimodifikasi dengan mengindeks atau slicing array. Array yang berbeda bisa berbagi data yang sama, jadi perubahan yang dibuat pada satu array mungkin terlihat di array lain.

Array attributes mencerminkan informasi intrinsik ke array itu sendiri. Jika kalian perlu mendapatkan, atau bahkan menyetel, properti dari sebuah array tanpa membuat sebuah array baru, kalian sering kali dapat mengakses sebuah array melalui atributnya.

**What’s the difference between a Python list and a NumPy array?**

NumPy memberi kalian berbagai macam opsi terkait numerik yang cepat dan efisien. Meskipun List Python dapat berisi tipe data yang berbeda dalam satu daftar, semua elemen dalam array NumPy harus homogen. Operasi matematika yang dimaksudkan untuk dilakukan pada array tidak akan mungkin dilakukan jika array

### Array

Creating Array

In [10]:
np.array()
np.zeros()
np.ones()
np.empty()
np.arange()

TypeError: array() missing required argument 'object' (pos 0)

Untuk membuat array NumPy, kalian dapat menggunakan fungsi np.array().

Yang perlu kalian lakukan untuk membuat array sederhana adalah dengan passing list ke dalamnya. Kalian juga dapat menentukan tipe data dalam List kalian.

In [3]:
import numpy as np 

a = np.array([1, 2, 3])
a

array([1, 2, 3])

Sering ada kasus ketika kita ingin NumPy menginisialisasi nilai array untuk kita. NumPy menyediakan metode seperti ones(), zeros(), dan lain-lain untuk kasus ini. Kitahanya memberikan mereka sejumlah elemen yang kita inginkan untuk di-generate:

In [4]:
# you can easily create an array filled with 0s:

np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [5]:
# Or an array filled with 1s:

np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [6]:
# Or even an empty array!
# The function empty creates an array whose initial content is random and depends on the state of the memory.

np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [8]:
# You can create an array with a range of elements

print(np.arange(4))
print(np.arange(0,10,2)) #(start, stop, step)

[0 1 2 3]
[0 2 4 6 8]


Apa yang dilakukan arange([start],stop,[step]) adalah mengatur angka dari awal sampai berhenti. Inil adalah arti dari np.arange(0,10,2):

list np mulai dari 0 hingga 10 tetapi jangan sertakan 10 dan buat angka tersebut melakukan kenaikan 2 setiap kali.

Hal penting yang perlu diingat di sini adalah bahwa angka berhenti (10) tidak akan dimasukkan dalam list. contoh lain:

In [10]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

### Add, Remove, and Sort

In [11]:
np.append()
np.delete()
np.sort()

TypeError: _append_dispatcher() missing 2 required positional arguments: 'arr' and 'values'

Jika kalian mulai dari array ini:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

Kalian bisa menambahkan elemen ke array kalian kapan saja dengan np.append(). Pastikan untuk menentukan array dan elemen yang ingin kalian sertakan.

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

Kalian bisa menghapus elemen dengan np.delete(). Jika kalian ingin menghapus elemen di posisi 1 dari array kalian, kalian dapat menjalankan:

In [14]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

Mengurutkan elemen dapat dilakukan dengan np.sort(). Kalian dapat menentukan axis, jenis, dan urutan saat Anda memanggil fungsi.

Jika kalian mulai dari array ini:

In [15]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

kalian dapat dengan cepat mengurutkan angka dalam urutan menaik dengan

In [16]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

### Shape and Size

In [ ]:
ndarray.ndim()
ndarray.size()
ndarray.shape()

ndarray.ndim akan memberi tahu kalian jumlah axes, atau dimensi, dari array.

ndarray.size akan memberi tahu kalian jumlah total elemen array. Ini adalah produk dari elemen shape array.

ndarray.shape akan menampilkan tuple integer yang menunjukkan jumlah elemen yang disimpan di sepanjang setiap dimensi array. Jika, misalnya, kalian memiliki larik 2D dengan 2 baris dan 3 kolom, maka bentuk larik Anda adalah (2,3).

In [27]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                           
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                            
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [28]:
array_example.ndim

3

In [29]:
array_example.size

24

In [30]:
array_example.shape

(3, 2, 4)

In [32]:
arr_one = np.array([[1, 2, 3, 4, 5]])
arr_one.ndim

2

In [33]:
arr_one.size

5

In [34]:
arr_one.shape

(1, 5)

### Reshape

In [ ]:
np.reshape()

Menggunakan np.reshape() akan memberikan bentuk baru ke array tanpa mengubah datanya. Ingatlah bahwa ketika kalian menggunakan metode reshape, array yang ingin kalian hasilkan harus memiliki jumlah elemen yang sama dengan array asli. Jika kalian memulai dengan sebuah array dengan 12 elemen, kalian harus memastikan bahwa array baru kalian juga memiliki total 12 elemen.

Jika kalian mulai dengan array ini:

In [36]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


You can use reshape() to reshape your array. For example, you can reshape this array to an array with three rows and two columns:

Kalian dapat menggunakan reshape() untuk membentuk kembali array kalian. Misalnya, kalian dapat membentuk kembali array ini menjadi array dengan tiga baris dan dua kolom:

In [37]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [38]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

dengan np.reshape kalian dapat menentukan beberapa parameter opsional:
numpy.reshape(a, newshape, order)

* ***a*** adalah array yang akan di-reshaped.
* **newshape** adalah bentuk baru yang kalian inginkan. Kalian dapat menentukan integer atau tuple integer. Jika kalian menentukan bilangan bulat, hasilnya adalah array dengan panjang bilangan tersebut. Bentuknya harus sesuai dengan bentuk aslinya.
* **order:** ‘C’ means to read/write the elements using C-like index order, ‘F’ means to read/write the elements using Fortran-like index order, ‘A’ means to read/write the elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise. (This is an optional parameter and doesn’t need to be specified.)
* **order:** 'C' berarti read/write elemen menggunakan C-like index order, 'F' berarti read/write elemen menggunakan Fortran-like index order, 'A' berarti read/write elemen dengan Fortran-like index order jika a adalah Fortran contiguous pada memory. (Ini adalah parameter opsional dan tidak perlu ditentukan.)

### Convert 1D to 2D

In [ ]:
np.newaxis
np.expand_dims

Kalian dapat menggunakan np.newaxis dan np.expand_dims untuk meningkatkan dimensi array yang sudah ada.

Menggunakan np.newaxis akan meningkatkan dimensi array kalian sebesar satu dimensi bila digunakan sekali. Artinya array 1D akan menjadi array 2D, array 2D akan menjadi array 3D, dan seterusnya.

Misalnya, jika kalian memulai dengan array ini:

In [42]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [43]:
a

array([1, 2, 3, 4, 5, 6])

In [45]:
# You can use np.newaxis to add a new axis:

a2 = a[np.newaxis]
print(a2.shape)
a2

(1, 6)


array([[1, 2, 3, 4, 5, 6]])

In [46]:
# You can convert a 1D array to a row vector by inserting an axis along the first dimension

row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)


(1, 6)
[[1 2 3 4 5 6]]


In [47]:
# for a column vector, You can insert an axis along the second dimension

col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


Kalian juga dapat memperluas array dengan memasukkan axis baru pada posisi yang ditentukan dengan np.expand_dims.

Misalnya, jika kalian memulai dengan array ini:

In [48]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [50]:
# You can use np.expand_dims to add an axis at index position 1 with:

b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [52]:
# You can add an axis at index position 0 with:

c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

### Indexing and Slicing

Kalian dapat mengindeks dan slice array NumPy dengan cara yang sama seperti kalian slice lists Python.

In [54]:
data = np.array([1, 2, 3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


Kalian mungkin ingin mengambil bagian dari array atau elemen array tertentu untuk digunakan dalam analisis lebih lanjut atau operasi tambahan. Untuk melakukannya, kalian perlu membuat subset, memotong, dan / atau mengindeks array kalian.

Jika kalian ingin memilih nilai dari array kalian yang memenuhi kondisi tertentu, dapat dilakukan langsung dengan NumPy.

Misalnya, jika kalian memulai dengan array ini:

In [55]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [59]:
# You can easily print all of the values in the array that are less than 5

print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


Kalian juga dapat memilih, misalnya, angka yang sama dengan atau lebih besar dari 5, dan menggunakan kondisi tersebut untuk mengindeks array.

In [60]:
five_up = (a >= 5)

print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [62]:
# You can select elements that are divisible by 2

divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [63]:
# you can select elements that satisfy two conditions using the & and | operators

c = a[(a > 2) & (a < 11)]

In [64]:
print(c)

[ 3  4  5  6  7  8  9 10]


### Creating Array from Existing Data

In [ ]:
slicing indexing
np.vstack()
np.hstack()
np.hsplit()
.view()
.copy()

ou can easily use create a new array from a section of an existing array. Let’s say you have this array:

Kalian dapat dengan mudah membuat array baru dari bagian array yang sudah ada. Misalkan kalian memiliki array ini:

array([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

Kalian dapat membuat array baru dari bagian array kalian kapan saja dengan menentukan di mana kalian ingin mengiris/slice array kalian.

In [67]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

kalian juga dapat menumpuk dua array yang ada, baik secara vertikal maupun horizontal. Misalkan kalian memiliki dua array:
a_1:

In [ ]:
array([[1, 1],
     [2, 2]])

and a_2:

In [ ]:
array([[3, 3],
     [4, 4]])

Kalian dapat menumpuk secara vertikal dengan vstack

In [71]:
a_1 = np.array([[1, 1],
                [2,2]])

In [72]:
a_2 = np.array([[3, 3],
                [4, 4]])

In [73]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [74]:
# Or stack them horizontally with hstack

np.hstack ((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

Kalian dapat membagi sebuah array menjadi beberapa array yang lebih kecil menggunakan hsplit. Kalian dapat menentukan jumlah array yang bentuknya sama untuk dikembalikan atau kolom setelah pembagian dilakukan.

Misalkan kalian memiliki larik ini:

In [ ]:
array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [76]:
arrsplit = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                     [13, 14, 15, 16, 17, 18 ,19, 20, 21, 22, 23, 24]])

print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [77]:
# If you wanted to split this array into three equally shaped arrays

np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

Kalian dapat menggunakan metode view untuk membuat objek array baru yang terlihat sama dengan array asli (shallow copy)

In [78]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8,], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [79]:
# You can create a new array object that looks at the same data

b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [81]:
# Using the copy method will make a complete copy of the array and its data (a deep copy).

c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Basic array operations

**Addition, subtraction, multiplication, division, and more**

Setelah kalian membuat array, kalian dapat mulai bekerja dengan array tersebut. Katakanlah, misalnya, kalian telah membuat dua array, satu disebut "data" dan satu lagi disebut "ones".

Kalian dapat menambahkan array tersebut dengan tanda tambah.

data + ones

Kalian tentu saja dapat melakukan lebih dari sekadar penjumlahan.

In [ ]:
data - ones
data * data
data / data

Operasi dasar sangat sederhana jika dilakukan dengan dengan NumPy. Jika kalian ingin menemukan hasil penjumlahan elemen dalam array, kalian dapat menggunakan sum(). Ini berfungsi untuk array1D, array2D, dan arraydalam dimensi yang lebih tinggi.

In [82]:
a = np.array([1, 2, 3, 4])

# add all of the elements in the array
a.sum()

10

Untuk menambahkan baris atau kolom dalam array 2D, kalian harus menentukan axis.

Jika kalian mulai dengan array ini:

In [83]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [84]:
# You can sum the rows

b.sum(axis=0)

array([3, 3])

In [85]:
# You can sum the columns

b.sum(axis=1)

array([2, 4])

In [86]:
data = np.array([1, 2])
data

array([1, 2])

In [87]:
ones = np.ones(2)
ones

array([1., 1.])

In [88]:
data + ones

array([2., 3.])

In [89]:
data * data

array([1, 4])

In [90]:
data / data

array([1., 1.])

### Broadcasting
Ada kalanya kalian mungkin ingin melakukan operasi antara array dan satu bilangan (juga disebut operasi antara vektor dan skalar) atau antara array dengan dua ukuran berbeda.

Misalnya, array kalian (kita menyebutnya "data") mungkin berisi informasi tentang jarak dalam mil tetapi Anda ingin mengonversi informasi menjadi kilometer. Kalian dapat melakukan operasi ini dengan:

data * 1.6

NumPy memahami bahwa perkalian harus dilakukan dengan setiap sel. Konsep tersebut disebut broadcasting.

Broadcasting adalah mekanisme yang memungkinkan NumPy melakukan operasi pada array dengan bentuk berbeda. Dimensi array kalian harus kompatibel, misalnya, jika dimensi kedua array sama atau salah satunya adalah 1. Jika dimensinya tidak kompatibel, kalian akan mendapatkan value error.

In [91]:
data * 2

array([2, 4])

### More Array Operations
Maximum, minimum, sum, mean, product, standard deviation, and more

NumPy juga melakukan fungsi agregasi. Selain min, max, dan sum, kalian bisa dengan mudah menjalankan mean untuk mendapatkan rata-rata, prod untuk mendapatkan hasil perkalian elemen, std untuk mendapatkan standard deviation, dan banyak lagi.

In [93]:
data.max()
data.min()
data.sum()

3

In [94]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


Sangat umum jika ingin menggabungkan sepanjang baris atau kolom. Secara default, setiap fungsi agregasi NumPy akan mengembalikan agregat dari seluruh array.

In [95]:
A.sum()

4.8595784

In [96]:
A.min()

0.05093587

In [97]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [98]:
A.max()

0.82485143

In [99]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [100]:
A.std()

0.21392120766089617

Empat nilai yang tercantum di atas sesuai dengan jumlah kolom dalam array kalian. Dengan array empat kolom, kalian akan mendapatkan empat nilai sebagai hasil kalian.

### Matrices
Kalian dapat meneruskan lists of lists Python untuk membuat matriks untuk mewakilinya di NumPy.

### Creating Matrices
np.array([[1,2],[3,4]])

Kita juga dapat menggunakan metode yang sama yang kita sebutkan di atas (ones(), zeros(), dan random.random()) selama kita memberi mereka tuple yang menggambarkan dimensi matriks yang kita buat

In [101]:
np.ones((3,2))
np.zeros((3,2))
np.random.random((3,2))

array([[0.47019136, 0.95068057],
       [0.79579735, 0.65586261],
       [0.61154645, 0.9049835 ]])

In [102]:
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.16582432 0.43074529]
 [0.06825788 0.62551187]
 [0.63039636 0.98738206]]


### Matrix Arithmetic
Kita dapat menjumlahkan dan mengalikan matriks menggunakan operator aritmatika (+ - * /) jika kedua matriks tersebut berukuran sama. NumPy menanganinya sebagai position-wise operations.

In [103]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [105]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [106]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [107]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [108]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


### Dot Product
NumPy memberi setiap matriks metode dot() yang dapat kita gunakan untuk menjalankan operasi dot product dengan matriks lain

In [110]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [111]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

### Matrix Indexing
Operasi Indexing dan slicing menjadi lebih berguna saat kita memanipulasi matriks

In [112]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


### Matrix Aggregation
Kita dapat menjumlahkan matriks dengan cara yang sama seperti kita menjumlahkan vektor

In [113]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [114]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [115]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


### Transposing and Reshaping
Kebutuhan umum saat menangani matriks adalah kebutuhan untuk rotate. Hal ini sering terjadi ketika kita perlu melakukan dot product dari dua matriks dan perlu menyelaraskan dimensi mereka. Array NumPy memiliki properti yang disebut T untuk mendapatkan transpos dari sebuah matriks.

In [116]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [117]:
print(data.T)

[[1 3 5]
 [2 4 6]]


Dalam kasus penggunaan yang lebih lanjut, kalian mungkin perlu mengganti dimensi matriks tertentu. Ini sering terjadi dalam aplikasi machine learning di mana model tertentu mengharapkan bentuk tertentu untuk masukan yang berbeda dari kumpulan data kalian.

Metode reshape() NumPy berguna dalam kasus ini. Kalian hanya memberikan dimensi baru yang kkalian inginkan untuk matriks. Kalian dapat meneruskan -1 untuk dimensi dan NumPy dapat menyimpulkan dimensi yang benar berdasarkan matriks Anda

In [119]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T #Transpose Matriks
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [120]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [121]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

Kalian juga dapat menggunakan np.transpose untuk membalikkan atau mengubah axes array sesuai dengan nilai yang kalian tentukan. Jika kalian mulai dengan array ini

In [124]:
arr = np.arange(6).reshape((2,3))
print(arr)

[[0 1 2]
 [3 4 5]]


### N-Dimensional Array
NumPy dapat melakukan semua yang telah kita sebutkan dalam berbagai dimensi. Struktur data pusatnya disebut ndarray (N-Dimensional Array) karena suatu alasan.

In [126]:
ndarr = np.array([[[1, 2],[3, 4],
                   [5,6], [7, 8]]])

print(ndarr)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


Dalam banyak hal, berurusan dengan dimensi baru hanyalah dengan menambahkan koma ke parameter fungsi NumPy

In [127]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [128]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [129]:
print(np.random.random((4,3,2)))

[[[0.60994884 0.14807352]
  [0.32612951 0.29933796]
  [0.77363465 0.17370112]]

 [[0.429786   0.69076593]
  [0.72288207 0.55762931]
  [0.73639321 0.24766049]]

 [[0.44505592 0.0435729 ]
  [0.64476508 0.50846104]
  [0.64740011 0.81489491]]

 [[0.73200557 0.36143175]
  [0.41099136 0.56431688]
  [0.3351892  0.27384141]]]


Flatten N-Dimensional Array
Ada dua cara populer untuk meratakan array: .flatten() dan.ravel(). Perbedaan utama antara keduanya adalah bahwa array baru yang dibuat menggunakanravel() sebenarnya merupakan referensi ke array induk. Ini berarti bahwa setiap perubahan pada array baru akan memengaruhi array induk juga. Karena ravel tidak membuat salinan, ini menghemat memori.

In [130]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [131]:
# You can use flatten to flatten your array into a 1D array.

arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

Working with Math Formulas
Mengimplementasikan rumus matematika yang bekerja pada array adalah salah satu hal yang membuat NumPy sangat dihargai di komunitas ilmiah Python.

Misalnya, ini adalah rumus mean square error (rumus utama yang digunakan dalam supervised machine learning model yang menangani regresi):

Menerapkan rumus ini sederhana dan mudah di NumPy:

In [ ]:
error = (1/n) * np.sum(np.square(observed - prediction))